name: 'Calculate Deployment Name'
description: 'Calculates valid deployment names based on repo name and branch name'
author: 'localsearch'
inputs:
  app: # change this
    required: true
    description: 'Application name (usually repo name)'
  branch:
    required: true
    description: 'Name of the current branch'
runs:
  using: 'node14'
  main: 'dist/index.js'
